drop table if exists es.dw_jxfp_main;
create table if not exists es.dw_jxfp_main (
    id string,
    fplb string,
    fplbmc string,
    fpdm string,
    fphm string,
    rzrq string,
    kprq string,
    gfnsrsbh string,
    gfnsrmc string,
    xfnsrsbh string,
    xfnsrmc string,
    je string,
    se string,
    gfswjgdm string,
    skm string,
    gfswjgmc string,
    fddbrmc string,
    frzjhm string,
    cwlxr string,
    scjydz string,
    jxfpid string,
    sjswjgdm string,
    datekey string,
    hydm string,
    mldm string,
    nsrmc string,
    nsrsbh string,
    swjglevel string,
    dkbz string,
    wdbz string,
	bz string
);
drop table if exists es.dw_jxfpmx_main;
create table if not exists es.dw_jxfpmx_main(
    id string ,
    jxfpid string,
    fplb string ,
    fplbmc string ,
    fpdm string ,
    fphm string ,
    rzrq string ,
    kprq string ,
    gfnsrsbh string ,
    gfnsrmc string ,
    xfnsrsbh string ,
    xfnsrmc string ,
    wpmc string ,
    wpxh string ,
    wpdw string ,
    wpsl string ,
    dj string ,
    je string ,
    sl string ,
    se string ,
    gfswjgdm string ,
    gfswjgmc string ,
    gfnsrkey string ,
    fddbrmc string ,
    frzjhm string ,
    cwlxr string ,
    scjydz string ,
    nsrmc string ,
    nsrsbh string,
    sjswjgdm string ,
    datekey string ,
    hydm string ,
    mldm string,
    swjglevel string,
    qdbz string,
    dkbz string,
    wdbz string,
	skm string,
	bz string
);
