create external table if not exists es.dw_jxfp_es(
    id string,
    fplb string,
    fplbmc string,
    fpdm string,
    fphm string,
    rzrq string,
    kprq string,
    gfnsrsbh string,
    gfnsrmc string,
    xfnsrsbh string,
    xfnsrmc string,
    je decimal(16,2),
    se decimal(16,2),
    gfswjgdm string,
    skm string,
    gfswjgmc string,
    fddbrmc string,
    frzjhm string,
    cwlxr string,
    scjydz string,
    jxfpid string,
    sjswjgdm string,
    datekey string,
    hydm string,
    mldm string,
    nsrmc string,
    nsrsbh string,
    swjglevel string,
    dkbz string,
    wdbz string
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'jxfp.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');

create external table if not exists es.dw_jxfpmx_es(
    id string ,
    jxfpid string,
    fplb string ,
    fplbmc string ,
    fpdm string ,
    fphm string ,
    rzrq string ,
    kprq string ,
    gfnsrsbh string ,
    gfnsrmc string ,
    xfnsrsbh string ,
    xfnsrmc string ,
    wpmc string ,
    wpxh string ,
    wpdw string ,
    wpsl string ,
    dj decimal(16,2) ,
    je decimal(16,2) ,
    sl string ,
    se decimal(16,2) ,
    gfswjgdm string ,
    gfswjgmc string ,
    gfnsrkey string ,
    fddbrmc string ,
    frzjhm string ,
    cwlxr string ,
    scjydz string ,
    nsrmc string ,
    nsrsbh string,
    sjswjgdm string ,
    datekey string ,
    hydm string ,
    mldm string,
    swjglevel string,
    qdbz string,
    dkbz string,
    wdbz string
)
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'jxfpmx.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');

create external table if not exists es.dw_xxfp_es(
    id string ,
    xxfpid string,
    fplb string ,
    fplbmc string ,
    fpdm string ,
    fphm string ,
    kprq string ,
    gfnsrsbh string ,
    gfnsrmc string ,
    xfnsrsbh string ,
    xfnsrmc string ,
    je decimal(16,2) ,
    se decimal(16,2) ,
    xjswjgdm string ,
    xjswjgmc string ,
    fddbrmc string ,
    frzjhm string ,
    cwlxr string ,
    scjydz string ,
    nsrsbh string ,
    sjswjgdm string ,
    datekey string ,
    hydm string ,
    mldm string,
    swjglevel string,
    dkbz string,
    wdbz string
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'xxfp.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');


create external table if not exists es.dw_xxfpmx_es(
    id string,
    fplb string,
    fplbmc string,
    fpdm string,
    fphm string,
    kprq string,
    gfnsrsbh string,
    gfnsrmc string,
    xfnsrsbh string,
    xfnsrmc string,
    wpmc string,
    wpxh string,
    wpdw string,
    wpsl string,
    dj decimal(16,2),
    je decimal(16,2),
    sl string,
    se decimal(16,2),
    xjswjgdm string,
    xjswjgmc string,
    fddbrmc string,
    frzjhm string,
    cwlxr string,
    scjydz string,
    xxfpid string,
    nsrsbh string,
    nsrmc  string,
    sjswjgdm string,
    datekey string,
    hydm  string,
    mldm string,
    swjglevel string,
    qdbz string,
    dkbz string,
    wdbz string
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'xxfpmx.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');


create external table if not exists es.dw_fplyd_es(
    id string ,
    fplb string ,
    fplbmc string ,
    fpdm string ,
    fphm string ,
    rzrq string ,
    kprq string ,
    gfnsrsbh string ,
    gfnsrmc string ,
    xfnsrsbh string ,
    xfnsrmc string ,
    je decimal(16,2) ,
    se decimal(16,2) ,
    gfswjgdm string ,
    gfswjgmc string ,
    fddbrmc string ,
    frzjhm string ,
    cwlxr string ,
    scjydz string ,
    jxfpid string ,
    sjswjgdm string ,
    datekey string ,
    hydm string,
    mldm string,
    dqdm string
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'fplyd.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');


create table if not exists es.dw_fplyd_mx_es(
    id string,
    fplb string,
    fplbmc string,
    fpdm string,
    fphm string,
    rzrq string,
    kprq string,
    gfnsrsbh string,
    gfnsrmc string,
    xfnsrsbh string,
    xfnsrmc string,
    wpmc string,
    wpxh string,
    wpdw string,
    wpsl string,
    dj decimal(16,2),
    je decimal(16,2),
    sl string,
    se decimal(16,2),
    gfswjgdm string,
    gfswjgmc string,
    gfnsrkey string,
    fddbrmc string,
    frzjhm string,
    cwlxr string,
    scjydz string,
    sjswjgdm string,
    datekey string,
    jxfpid string,
    hydm string,
    mldm string,
    dqdm string,
    qdbz string
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'fplyd_mx.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');

create external table if not exists es.dw_fplxd_es(
    id string,
    fplb string,
    fplbmc string,
    fpdm string,
    fphm string,
    kprq string,
    gfnsrsbh string,
    gfnsrmc string,
    xfnsrsbh string,
    xfnsrmc string,
    je decimal(16,2),
    se decimal(16,2),
    xjswjgdm string,
    xjswjgmc string,
    fddbrmc string,
    frzjhm string,
    cwlxr string,
    scjydz string,
    xxfpid string,
    sjswjgdm string,
    dqdm string,
    datekey string,
    hydm string,
    mldm string
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'fplxd.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');

create table if not exists es.dw_fplxd_mx_es(
    id string,
    fplb string,
    fplbmc string,
    fpdm string,
    fphm string,
    kprq string,
    gfnsrsbh string,
    gfnsrmc string,
    xfnsrsbh string,
    xfnsrmc string,
    wpmc string,
    wpxh string,
    wpdw string,
    wpsl string,
    dj decimal(16,2),
    je decimal(16,2),
    sl string,
    se decimal(16,2),
    xjswjgdm string,
    xjswjgmc string,
    fddbrmc string,
    frzjhm string,
    cwlxr string,
    scjydz string,
    xxfpid string,
    sjswjgdm string,
    datekey string,
    dqdm string,
    hydm string,
    mldm string,
    qdbz string
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'fplxd_mx.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');

create external table if not exists es.dw_hwl_jx_es(
    id string,
    wpmc string,
    je decimal(16,2),
    se decimal(16,2),
    wp_sl decimal(16,2),
    fpfs string,
    fplb string,
    fplbmc string,
    wpdw string,
    nsrsbh string,
    datekey string
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'hwl_jx.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');


create external table if not exists es.dw_hwl_xx_es(
    id string,
    wpmc string,
    je decimal(16,2),
    se decimal(16,2),
    wp_sl decimal(16,2),
    fpfs string,
    fplb string,
    fplbmc string,
    wpdw string,
    nsrsbh string,
    datekey string
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'hwl_xx.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');



create external table if not exists es.dw_jxxcy_jx_es(
    id string,
    wpmc string,
    je decimal(16,2),
    se decimal(16,2),
    wp_sl decimal(16,2),
    fpfs string,
    fplb string,
    fplbmc string,
    wpdw string,
    nsrsbh string,
    datekey string
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'jxxcy_jx.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');


create external table if not exists es.dw_jxxcy_xx_es(
    id string,
    wpmc string,
    je decimal(16,2),
    se decimal(16,2),
    wp_sl decimal(16,2),
    fpfs string,
    fplb string,
    fplbmc string,
    wpdw string,
    nsrsbh string,
    datekey string
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'jxxcy_xx.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');



 create table if not exists es.dw_zgkpxe_es(
    ID string,
    fplb string,
    fplbmc string,
    fpdm string,
    fphm string,
    kprq string,
    gfnsrsbh string,
    gfnsrmc string,
    xfnsrsbh string,
    xfnsrmc string,
    je decimal(16,2),
    se decimal(16,2),
    fddbrmc string,
    frzjhm string,
    cwlxr string,
    scjydz string,
    xxfpid string,
    datekey  string             
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'                                                     
TBLPROPERTIES('es.resource' = 'zgkpxe.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');        


create table if not exists es.dw_zgkpxe_mx_es(
    id string,
    fplb string,
    fplbmc string,
    fpdm string,
    fphm string,
    kprq string,
    gfnsrsbh string,
    gfnsrmc string,
    xfnsrsbh string,
    xfnsrmc string,
    je decimal(16,2),
    se decimal(16,2),
    fddbrmc string,
    frzjhm string,
    cwlxr string,
    scjydz string,
    wpmc string,
    wpxh string,
    wpdw string,
    wpsl string,
    sl string,
    dj decimal(16,2),
    xxfpid string,
    datekey string,
    qdbz string
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'zgkpxe_mx.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');


create external table if not exists es.dw_xxfpmxzf_es(
    id string,
    fplb string,
    fplbmc string,
    fpdm string,
    fphm string,
    kprq string,
    zfsj string,
    gfnsrsbh string,
    gfnsrmc string,
    xfnsrsbh string,
    xfnsrmc string,
    wpmc string,
    wpxh string,
    wpdw string,
    wpsl string,
    dj decimal(16,2),
    je decimal(16,2),
    sl string,
    se decimal(16,2),
    xjswjgdm string,
    xjswjgmc string,
    fddbrmc string,
    frzjhm string,
    cwlxr string,
    scjydz string,
    xxfpid string,
    nsrsbh string,
    nsrmc  string,
    sjswjgdm string,
    datekey string,
    hydm  string,
    mldm string,
    swjglevel string,
    qdbz string
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'xxfpmx_zf.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');


create external table if not exists es.dw_xxfpzf_es(
    id string ,
    xxfpid string,
    fplb string ,
    fplbmc string ,
    fpdm string ,
    fphm string ,
    kprq string ,
    zfsj string,
    gfnsrsbh string ,
    gfnsrmc string ,
    xfnsrsbh string ,
    xfnsrmc string ,
    je decimal(16,2) ,
    se decimal(16,2) ,
    xjswjgdm string ,
    xjswjgmc string ,
    fddbrmc string ,
    frzjhm string ,
    cwlxr string ,
    scjydz string ,
    nsrsbh string ,
    sjswjgdm string ,
    datekey string ,
    hydm string ,
    mldm string,
    swjglevel string
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'xxfp_zf.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');


create external table if not exists es.dw_skfp_es(
    id string ,
    xxfpid string,
    fplb string ,
    fplbmc string ,
    fpdm string ,
    fphm string ,
    kprq string ,
    gfnsrsbh string ,
    gfnsrmc string ,
    xfnsrsbh string ,
    xfnsrmc string ,
    je decimal(16,2) ,
    se decimal(16,2) ,
    xjswjgdm string ,
    xjswjgmc string ,
    fddbrmc string ,
    frzjhm string ,
    cwlxr string ,
    scjydz string ,
    nsrsbh string ,
    sjswjgdm string ,
    datekey string ,
    hydm string ,
    mldm string,
    swjglevel string,
    dkbz string,
    rzjg string
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'skfp.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');

create external table if not exists es.dw_skfpmx_es(
    id string,
    fplb string,
    fplbmc string,
    fpdm string,
    fphm string,
    kprq string,
    gfnsrsbh string,
    gfnsrmc string,
    xfnsrsbh string,
    xfnsrmc string,
    wpmc string,
    wpxh string,
    wpdw string,
    wpsl string,
    dj string,
    je decimal(16,2),
    sl string,
    se decimal(16,2),
    xjswjgdm string,
    xjswjgmc string,
    fddbrmc string,
    frzjhm string,
    cwlxr string,
    scjydz string,
    xxfpid string,
    nsrsbh string,
    nsrmc  string,
    sjswjgdm string,
    datekey string,
    hydm  string,
    mldm string,
    swjglevel string,
    qdbz string,
    dkbz string,
    rzjg string
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'skfpmx.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');


create external table if not exists es.dw_jxfp_zf_es(
    id string,
    fplb string,
    fplbmc string,
    fpdm string,
    fphm string,
    rzrq string,
    kprq string,
    gfnsrsbh string,
    gfnsrmc string,
    xfnsrsbh string,
    xfnsrmc string,
    je decimal(16,2),
    se decimal(16,2),
    gfswjgdm string,
    skm string,
    gfswjgmc string,
    fddbrmc string,
    frzjhm string,
    cwlxr string,
    scjydz string,
    jxfpid string,
    sjswjgdm string,
    datekey string,
    hydm string,
    mldm string,
    nsrmc string,
    nsrsbh string,
    swjglevel string,
    dkbz string,
    zfsj string
)STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'jxfp_zf.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');




create external table if not exists es.dw_jxfpmx_zf_es(
    id string ,
    jxfpid string,
    fplb string ,
    fplbmc string ,
    fpdm string ,
    fphm string ,
    rzrq string ,
    kprq string ,
    gfnsrsbh string ,
    gfnsrmc string ,
    xfnsrsbh string ,
    xfnsrmc string ,
    wpmc string ,
    wpxh string ,
    wpdw string ,
    wpsl string ,
    dj decimal(16,2) ,
    je decimal(16,2) ,
    sl string ,
    se decimal(16,2) ,
    gfswjgdm string ,
    gfswjgmc string ,
    gfnsrkey string ,
    fddbrmc string ,
    frzjhm string ,
    cwlxr string ,
    scjydz string ,
    nsrmc string ,
    nsrsbh string,
    sjswjgdm string ,
    datekey string ,
    hydm string ,
    mldm string,
    swjglevel string,
    qdbz string,
    dkbz string,
    zfsj string
)
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'jxfpmx_zf.list/list','es.mapping.id' = 'id','es.batch.write.retry.count'='-1','es.nodes'='${hivevar:es_nodes}');

