drop table if exists yh_dw.dw_xxfp_spare;
create table if not exists yh_dw.dw_xxfp_spare
(
    id string ,
    xxfpid string,
    fplb string ,
    fplbmc string ,
    fpdm string ,
    fphm string ,
    kprq string ,
    gfnsrsbh string ,
    gfnsrmc string ,
    xfnsrsbh string ,
    xfnsrmc string ,
    je string ,
    se string ,
    xjswjgdm string ,
    xjswjgmc string ,
    fddbrmc string ,
    frzjhm string ,
    cwlxr string ,
    scjydz string ,
    nsrsbh string ,
    sjswjgdm string ,
    datekey string ,
    hydm string ,
    mldm string ,
    swjglevel string,
    dkbz string,
    wdbz string,
    kpsj string,
	skm string,
	bz string
);

drop table if exists yh_dw.dw_xxfpmx_spare;
create table if not exists yh_dw.dw_xxfpmx_spare(
    id string,
    fplb string,
    fplbmc string,
    fpdm string,
    fphm string,
    kprq string,
    gfnsrsbh string,
    gfnsrmc string,
    xfnsrsbh string,
    xfnsrmc string,
    wpmc string,
    wpxh string,
    wpdw string,
    wpsl string,
    dj string,
    je string,
    sl string,
    se string,
    xjswjgdm string,
    xjswjgmc string,
    fddbrmc string,
    frzjhm string,
    cwlxr string,
    scjydz string,
    xxfpid string,
    nsrsbh string,
    nsrmc  string,
    sjswjgdm string,
    datekey string,
    hydm  string,
    mldm string,
    swjglevel string,
    qdbz string,
    dkbz string,
    wdbz string,
    kpsj string,
	skm string,
	bz string
);
 
 
 