set hive.auto.convert.join=false;
insert into dw.dw_hbase_nsr
select nsr.rowkey rowkey,map() nsrxx,
map('nsrmc_yw',COALESCE(kz.nsrmc_yw,''),'gshbz',COALESCE(kz.gshbz,''),'frbz',COALESCE(kz.frbz,''),'zcdz',COALESCE(kz.zcdz,''),'zcd_yb',COALESCE(kz.zcd_yb,''),
'scjyd_yb',COALESCE(kz.scjyd_yb,''),'dydz',COALESCE(kz.dydz,''),'gskyrq',COALESCE(cast(kz.gskyrq as string),''),'hsxs_dm',COALESCE(kz.hsxs_dm,''),'bsr_zjlx_dm',
COALESCE(kz.bsr_zjlx_dm,''),'bsr_zjhm',COALESCE(kz.bsr_zjhm,''),'jsjdjdm',COALESCE(kz.jsjdjdm,''),'gsdjjg_mc',COALESCE(kz.gsdjjg_mc,''),'zzlb_dm',COALESCE(kz.zzlb_dm,''),
'gsdjzzh',COALESCE(kz.gsdjzzh,''),'yxq_q',COALESCE(cast(kz.yxq_q as string),''),'yxq_z',COALESCE(cast(kz.yxq_z as string),''),'zy',COALESCE(kz.zy,''),'jy',COALESCE(kz.jy,''),
'jyfs',COALESCE(kz.jyfs,''),'scjyqx_q',COALESCE(cast(kz.scjyqx_q as string),''),'scjyqx_z',COALESCE(cast(kz.scjyqx_z as string),''),'gsfzrq',COALESCE(cast(kz.gsfzrq as string),''),
'zczb',COALESCE(kz.zczb,''),'zcbz_dm',COALESCE(kz.zcbz_dm,''),'tzze',COALESCE(kz.tzze,''),'tzbz_dm',COALESCE(kz.tzbz_dm,''),'cyrs',COALESCE(kz.cyrs,''),'wjrs',COALESCE(kz.wjrs,''),
'yzzz',COALESCE(kz.yzzz,''),'zgdw',COALESCE(kz.zgdw,''),'jyfwdw',COALESCE(kz.jyfwdw,''),'zjgyb',COALESCE(kz.zjgyb,''),'pzjg',COALESCE(kz.pzjg,''),'pzwh',COALESCE(kz.pzwh,''),
'pzrq',COALESCE(cast(kz.pzrq as string),''),'zhzcqk',COALESCE(kz.zhzcqk,''),'cjq_q',COALESCE(cast(kz.cjq_q as string),''),'cjq_z',COALESCE(cast(kz.cjq_z as string),''),
'hwcfc',COALESCE(kz.hwcfc,''),'hwcfdmj',COALESCE(kz.hwcfdmj,''),'cwfzrmc',COALESCE(kz.cwfzrmc,''),'cwbbzl',COALESCE(kz.cwbbzl,''),'gdzczjfs',COALESCE(kz.gdzczjfs,''),
'yhptxff',COALESCE(kz.yhptxff,''),'kjnd',COALESCE(kz.kjnd,''),'jzbwb_dm',COALESCE(kz.jzbwb_dm,''),'jzlb',COALESCE(kz.jzlb,''),'jzfs',COALESCE(kz.jzfs,''),'jzrq',COALESCE(kz.jzrq,''),
'fzrq',COALESCE(cast(kz.fzrq as string),''),'nsr_swjg_dm',COALESCE(kz.nsr_swjg_dm,''),'swjg_dm',COALESCE(kz.swjg_dm,''),'lrr_dm',COALESCE(kz.lrr_dm,''),
'lrrq',COALESCE(cast(kz.lrrq as string),''),'xgr_dm',COALESCE(kz.xgr_dm,''),'xgrq',COALESCE(cast(kz.xgrq as string),''),'hymx_dm',COALESCE(kz.hymx_dm,''),'bgly',COALESCE(kz.bgly,''),
'zcd_dhhm',COALESCE(kz.zcd_dhhm,''),'hsfs_dm',COALESCE(kz.hsfs_dm,''),'sykjzd_dm',COALESCE(kz.sykjzd_dm,''),'wzwz',COALESCE(kz.wzwz,''),'fr_dhhm',COALESCE(kz.fr_dhhm,''),'fr_yddhhm',
COALESCE(kz.fr_yddhhm,''),'fr_dydz',COALESCE(kz.fr_dydz,''),'cwfzr_zjlx_dm',COALESCE(kz.cwfzr_zjlx_dm,''),'cwfzr_zjhm',COALESCE(kz.cwfzr_zjhm,''),'cwfzr_dhhm',COALESCE(kz.cwfzr_dhhm,''),
'cwfzr_yddhhm',COALESCE(kz.cwfzr_yddhhm,''),'cwfzr_dydz',COALESCE(kz.cwfzr_dydz,''),'bsr_dhhm',COALESCE(kz.bsr_dhhm,''),'bsr_yddhhm',COALESCE(kz.bsr_yddhhm,''),'bsr_dydz',
COALESCE(kz.bsr_dydz,''),'swdlrmc',COALESCE(kz.swdlrmc,''),'swdlr_nsrsbh',COALESCE(kz.swdlr_nsrsbh,''),'swdlr_dhhm',COALESCE(kz.swdlr_dhhm,''),'swdlr_dydz',COALESCE(kz.swdlr_dydz,''),
'dszgswjg_j_dm',COALESCE(kz.dszgswjg_j_dm,''),'dszgswjg_dm',COALESCE(kz.dszgswjg_dm,''),'hhrs',COALESCE(kz.hhrs,''),'gdrs',COALESCE(kz.gdrs,''),'zrrtzbl',COALESCE(kz.zrrtzbl,''),
'wztzbl',COALESCE(kz.wztzbl,''),'gytzbl',COALESCE(kz.gytzbl,''),'fbzl',COALESCE(kz.fbzl,''),'fshy1_dm',COALESCE(kz.fshy1_dm,''),'fshy2_dm',COALESCE(kz.fshy2_dm,''),'fshy3_dm',
COALESCE(kz.fshy3_dm,''),'jyfw',COALESCE(kz.jyfw,''),'kyslrq',COALESCE(cast(kz.kyslrq as string),''),'nsywfsrq',COALESCE(cast(kz.nsywfsrq as string),''),'lghbz',COALESCE(kz.lghbz,''),
'lhbzbz',COALESCE(kz.lhbzbz,''),'xysbz',COALESCE(kz.xysbz,''),'zszzsydwbz',COALESCE(kz.zszzsydwbz,''),'fshy1_hymx_dm',COALESCE(kz.fshy1_hymx_dm,''),'fshy2_hymx_dm',
COALESCE(kz.fshy2_hymx_dm,''),'fshy3_hymx_dm',COALESCE(kz.fshy3_hymx_dm,''),'jdcxsqybz',COALESCE(kz.jdcxsqybz,''),'sfclgjxzjzhy',COALESCE(kz.sfclgjxzjzhy,''),'dqyglcj_dm',
COALESCE(kz.dqyglcj_dm,''),'hyfpzkpqy',COALESCE(kz.hyfpzkpqy,''),'sfwtlxgnsr',COALESCE(kz.sfwtlxgnsr,''),'scjydlxdh',COALESCE(kz.scjydlxdh,''),'bsrxm',COALESCE(kz.bsrxm,''),
'zczbbzy_dm',COALESCE(kz.zczbbzy_dm,''),'zczbbze_dm',COALESCE(kz.zczbbze_dm,''),'zczbbzs_dm',COALESCE(kz.zczbbzs_dm,''),'zczbbzyje',COALESCE(kz.zczbbzyje,''),'zczbbzeje',
COALESCE(kz.zczbbzeje,''),'zczbbzsje',COALESCE(kz.zczbbzsje,''),'tzzebzy_dm',COALESCE(kz.tzzebzy_dm,''),'tzzebze_dm',COALESCE(kz.tzzebze_dm,''),'tzzebzs_dm',COALESCE(kz.tzzebzs_dm,''),
'tzzebzyje',COALESCE(kz.tzzebzyje,''),'tzzebzeje',COALESCE(kz.tzzebzeje,''),'tzzebzsje',COALESCE(kz.tzzebzsje,''),'zzjglx_dm',COALESCE(kz.zzjglx_dm,''),'zfjglx_dm',COALESCE(kz.zfjglx_dm,'')) nsrkz,
map() nsrrd,
map() ckts,
map() hy,
map() fppz,
map() swjg,
map() region,
from_unixtime(unix_timestamp(),'yyyy-MM-dd') czsj 
from etl.etl_nsrkz kz join dw.dw_hbase_nsr nsr on kz.nsrdzdah = nsr.nsrxx['nsrdzdah'];
insert into dw.dw_hbase_nsr
select nsr.rowkey rowkey,map() nsrxx,
map() nsrkz,
map() nsrrd,
map() ckts,
map('hy_key',COALESCE(h.hy_key,''),'hy_dm',COALESCE(h.hy_dm,''),'hy_mc',COALESCE(h.hy_mc,''),'hymx_dm',COALESCE(h.hymx_dm,''),
'hymx_mc',COALESCE(h.hymx_mc,''),'yxbz',COALESCE(h.yxbz,''),'hydl_dm',COALESCE(h.hydl_dm,''),'hydl_mc',COALESCE(h.hydl_mc,''),
'hyml_dm',COALESCE(h.hyml_dm,''),'hyml_mc',COALESCE(h.hyml_mc,'')) hy,
map() fppz,
map() swjg,
map() region,
from_unixtime(unix_timestamp(),'yyyy-MM-dd') czsj 
from etl.etl_nsrkz kz join dw.dw_hbase_nsr nsr on kz.nsrdzdah = nsr.nsrxx['nsrdzdah'] join dw.dw_dim_hy h on kz.hymx_dm = h.hy_key where kz.hymx_dm is not null and kz.hymx_dm <>'';
set hive.auto.convert.join=true;
