#!/bin/bash

if [ $# -lt 2 ]; then
  echo  "The usage is :  sparksubmit.sh classname jarfilename param1 ..." 
else
# ${sparkexepath}/spark-submit --master local[24] --driver-memory 6G --executor-memory 6G --num-executors 5 --executor-cores 2 --conf spark.network.timeout=600000 --conf spark.default.parallelism=120  --jars ${LibPath}/ojdbc14.jar,${LibPath}/mysql-connector-java-5.1.38-bin.jar,${LibPath}/hbase-client-0.98.17-hadoop2.jar,${LibPath}/hbase-common-0.98.17-hadoop2.jar,${LibPath}/hbase-protocol-0.98.17-hadoop2.jar,${LibPath}/hbase-server-0.98.17-hadoop2.jar,${LibPath}/hive-hbase-handler-1.2.1.jar,${LibPath}/guava-12.0.1.jar,${LibPath}/protobuf-java-2.5.0.jar,${LibPath}/htrace-core-2.04.jar,${LibPath}/zookeeper-3.4.6.jar,${LibPath}/spark-streaming-kafka-assembly_2.10-1.3.1.jar,${LibPath}/IKAnalyzer2012_u6.jar,${LibPath}/postgresql-9.2-1002-jdbc4.jar --class $@


${sparkexepath}/spark-submit --master yarn --deploy-mode client --driver-memory 10G --executor-memory 12G --num-executors 15 --executor-cores 4 --conf spark.network.timeout=600000 --conf spark.default.parallelism=120  --jars ${LibPath}/ibatis-common-2.jar,${LibPath}/accessors-smart-1.1.jar,${LibPath}/asm-5.0.3.jar,${LibPath}/json-smart-2.2.1.jar,${LibPath}/elasticsearch-spark-1.2_2.10-2.3.2.jar,${LibPath}/ojdbc14.jar,${LibPath}/mysql-connector-java-5.1.38-bin.jar,${LibPath}/hbase-client-0.98.17-hadoop2.jar,${LibPath}/hbase-common-0.98.17-hadoop2.jar,${LibPath}/hbase-protocol-0.98.17-hadoop2.jar,${LibPath}/hbase-server-0.98.17-hadoop2.jar,${LibPath}/hive-hbase-handler-1.2.1.jar,${LibPath}/guava-12.0.1.jar,${LibPath}/protobuf-java-2.5.0.jar,${LibPath}/htrace-core-2.04.jar,${LibPath}/zookeeper-3.4.6.jar,${LibPath}/spark-streaming-kafka-assembly_2.10-1.3.1.jar,${LibPath}/IKAnalyzer2012_u6.jar,${LibPath}/postgresql-9.2-1002-jdbc4.jar --class $@    

#${sparkexepath}/spark-submit --master yarn --deploy-mode client --driver-memory 4G --executor-memory 4G --num-executors 16 --executor-cores 4 --conf spark.network.timeout=600000 --conf spark.default.parallelism=120  --jars ${LibPath}/ojdbc14.jar,${LibPath}/mysql-connector-java-5.1.38-bin.jar,${LibPath}/hbase-client-0.98.17-hadoop2.jar,${LibPath}/hbase-common-0.98.17-hadoop2.jar,${LibPath}/hbase-protocol-0.98.17-hadoop2.jar,${LibPath}/hbase-server-0.98.17-hadoop2.jar,${LibPath}/hive-hbase-handler-1.2.1.jar,${LibPath}/guava-12.0.1.jar,${LibPath}/protobuf-java-2.5.0.jar,${LibPath}/htrace-core-2.04.jar,${LibPath}/zookeeper-3.4.6.jar,${LibPath}/spark-streaming-kafka-assembly_2.10-1.3.1.jar,${LibPath}/IKAnalyzer2012_u6.jar,${LibPath}/postgresql-9.2-1002-jdbc4.jar --class $@    

# ${sparkexepath}/spark-submit --master yarn --deploy-mode client --driver-memory 4G --executor-memory 8G --num-executors 21 --executor-cores 8   --conf spark.default.parallelism=120 --conf spark.storage.memoryFraction=0.4 --conf spark.shuffle.memoryFraction=0.4   --jars ${LibPath}/ojdbc14.jar,${LibPath}/mysql-connector-java-5.1.38-bin.jar,${LibPath}/hbase-client-0.98.17-hadoop2.jar,${LibPath}/hbase-common-0.98.17-hadoop2.jar,${LibPath}/hbase-protocol-0.98.17-hadoop2.jar,${LibPath}/hbase-server-0.98.17-hadoop2.jar,${LibPath}/hive-hbase-handler-1.2.1.jar,${LibPath}/guava-12.0.1.jar,${LibPath}/protobuf-java-2.5.0.jar,${LibPath}/htrace-core-2.04.jar,${LibPath}/zookeeper-3.4.6.jar,${LibPath}/spark-streaming-kafka-assembly_2.10-1.3.1.jar,${LibPath}/IKAnalyzer2012_u6.jar,${LibPath}/postgresql-9.2-1002-jdbc4.jar --class $@     

fi
